### PR TITLE
Split Email

### PR DESCRIPTION
**Pull request by Beat-YT**

### CODE REVIEW

**Comment by Beat-YT** [comment]
Fuck it

**Comment by Lawin0129** [comment]
I never saw this bro im so sorry, You can open this back up if you'd like and i'll merge it

**Comment by Beat-YT** [comment]
[`d418c8c` (#4)](https://github.com/Lawin0129/LawinServer/pull/4/commits/d418c8c469f95eaf83f7e79c647bd07c5089eb01#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R894)

**Comment by Lawin0129** [comment]
ohh yeah, just change that then copy and paste it to start a new pull request

**Comment by Lawin0129** [comment]
oh

**Pull request closed without merging**
